name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload to server
        uses: lattepress/WordPress-Site-Deploy@stable
        with:
          url: "sftp://zx407606@zx407606.ftp.tools:22/"
          username: "zx407606"
          password: "%f5_Gb7R"
          options: --auto-init --insecure -vv
